sf4/src/Entity/Advert.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdvertRepository")
 */
class Advert
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $cart_year;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_km;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_days;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCartYear(): ?int
    {
        return $this->cart_year;
    }

    public function setCartYear(int $cart_year): self
    {
        $this->cart_year = $cart_year;

        return $this;
    }

    public function getNbKm(): ?int
    {
        return $this->nb_km;
    }

    public function setNbKm(int $nb_km): self
    {
        $this->nb_km = $nb_km;

        return $this;
    }

    public function getNbDays(): ?int
    {
        return $this->nb_days;
    }

    public function setNbDays(int $nb_days): self
    {
        $this->nb_days = $nb_days;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
}

sf4/src/Form/AdvertType.php
<?php

namespace App\Form;

use App\Entity\Advert;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdvertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('city')
            ->add('cart_year')
            ->add('nb_km')
            ->add('nb_days')
            ->add('price')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Advert::class,
        ]);
    }
}

sf4/src/Controller/AdvertController.php
<?php

namespace App\Controller;

use App\Entity\Advert;
use App\Form\AdvertType;
use App\Repository\AdvertRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/advert")
 */
class AdvertController extends AbstractController
{
    /**
     * @Route("/", name="advert_index", methods={"GET"})
     */
    public function index(AdvertRepository $advertRepository): Response
    {
        return $this->render('advert/index.html.twig', [
            'adverts' => $advertRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="advert_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $advert = new Advert();
        $form = $this->createForm(AdvertType::class, $advert);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($advert);
            $entityManager->flush();

            return $this->redirectToRoute('advert_index');
        }

        return $this->render('advert/new.html.twig', [
            'advert' => $advert,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="advert_show", methods={"GET"})
     */
    public function show(Advert $advert): Response
    {
        return $this->render('advert/show.html.twig', [
            'advert' => $advert,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="advert_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Advert $advert): Response
    {
        $form = $this->createForm(AdvertType::class, $advert);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('advert_index');
        }

        return $this->render('advert/edit.html.twig', [
            'advert' => $advert,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="advert_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Advert $advert): Response
    {
        if ($this->isCsrfTokenValid('delete'.$advert->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($advert);
            $entityManager->flush();
        }

        return $this->redirectToRoute('advert_index');
    }
}

sf4/templates/advert/_delete_form.html.twig
<form method="post" action="{{ path('advert_delete', {'id': advert.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ advert.id) }}">
    <button class="btn">Delete</button>
</form>

sf4/templates/advert/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

sf4/templates/advert/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Advert{% endblock %}

{% block body %}
    <h1>Edit Advert</h1>

    {{ include('advert/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('advert_index') }}">back to list</a>

    {{ include('advert/_delete_form.html.twig') }}
{% endblock %}

sf4/templates/advert/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des annonces de voitures{% endblock %}

{% block body %}
    <h1>Liste des annonces de voitures</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>City</th>
                <th>Cart_year</th>
                <th>Nb_km</th>
                <th>Nb_days</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for advert in adverts %}
            <tr>
                <td>{{ advert.id }}</td>
                <td>{{ advert.title }}</td>
                <td>{{ advert.description }}</td>
                <td>{{ advert.city }}</td>
                <td>{{ advert.cartYear }}</td>
                <td>{{ advert.nbKm }}</td>
                <td>{{ advert.nbDays }}</td>
                <td>{{ advert.price }}</td>
                <td>
                    <a href="{{ path('advert_show', {'id': advert.id}) }}">show</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

sf4/templates/advert/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Advert{% endblock %}

{% block body %}
    <h1>Create new Advert</h1>

    {{ include('advert/_form.html.twig') }}

    <a href="{{ path('advert_index') }}">back to list</a>
{% endblock %}

sf4/templates/advert/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Advert{% endblock %}

{% block body %}
    <h1>Advert</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ advert.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ advert.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ advert.description }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ advert.city }}</td>
            </tr>
            <tr>
                <th>Cart_year</th>
                <td>{{ advert.cartYear }}</td>
            </tr>
            <tr>
                <th>Nb_km</th>
                <td>{{ advert.nbKm }}</td>
            </tr>
            <tr>
                <th>Nb_days</th>
                <td>{{ advert.nbDays }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ advert.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('advert_index') }}">back to list</a>

    <a href="{{ path('advert_edit', {'id': advert.id}) }}">edit</a>

    {{ include('advert/_delete_form.html.twig') }}
{% endblock %}